name: Release
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

     - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.2
          haxelib install flixel 5.2.2
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.10.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxvlc 1.2.0
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib install hscript 2.5.0
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git extension-androidtools https://github.com/Default-name123/oldtools.git
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel-addons 2.10.0
          haxelib set flixel 5.2.2
          haxelib set openfl 9.2.2
          haxelib set lime 8.0.2
          haxelib set hxvlc 1.2.0
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -release

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
  Publish:
    needs: Android
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: ${{github.workspace}}

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          prerelease: false
          automatic_release_tag: 'v1.0.0'
          title: ' Android Port v1.0.0'
          files: ${{github.workspace}}/FNF Rodentrap-debug.apk
